### ISSUE TITLE
Add 'auto' to the Google Analytics tracker create method.

### ISSUE THREAD

**Issue by JosefJezek** [cesarwbr/google-analytics-element#10]
- https://github.com/h5bp/html5-boilerplate/pull/1562
- https://github.com/philipwalton/html5-boilerplate/commit/195499a86dedcea162da6e82fec14bd36dc7a10e
- https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by cesarwbr** [comment]
Thanks!
