### ISSUE TITLE
How to use this script

### ISSUE THREAD

**Issue by damNor** [cesarwbr/google-analytics-element#13]
I've already install this script via bower , but the google analytics data still doesn't show. DId i miss something...?

**Comment by cesarwbr** [comment]
Hi damNor! It's working. I've tested it and it's working now.
- Check if your google analytics tracking code is correct.
- How is your HTML file? Your HTML should look like this:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="bower_components/google-analytics/google-analytics.html">
</head>
<body>
    <!-- your content here -->

   <!-- here is the google-analytics component, the UA-XXXXXXX should be your google analytics tracking code -->
    <google-analytics code="UA-XXXXXXX"></google-analytics>
</body>
</html>
```

**Comment by damNor** [comment]
Hi cesar, the html file is exactly the same as demo.html and the tracking code is correct , but when i'm run it on localhost, don't appear anything just a blank page , with no error in console ( i'm using chrome ). PLease help.

**Comment by damNor** [comment]
Does this script need google signin api credential just like in this link https://github.com/GoogleWebComponents/google-analytics ?

**Comment by cesarwbr** [comment]
Hi damNor,
I've tested it on localhost and it is working as well. And you don't need google signing api credential.
Could you send your code?

**Comment by damNor** [comment]
my code is exactly the same as your code.

**Comment by damNor** [comment]
here is the screenshot : [image 1](http://railwaydigital.com/ga/screenshot-1.jpg) &   [image 2](http://railwaydigital.com/ga/screenshot-2.jpg)
